# Generated by Django 4.1 on 2022-08-28 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('codEmp', models.IntegerField(primary_key=True, serialize=False)),
                ('nomeEmp', models.CharField(max_length=10)),
                ('CNPJ', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioTEF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.BooleanField(default=False)),
                ('criar_empresa', models.BooleanField(default=False)),
                ('criar_usuario', models.BooleanField(default=False)),
                ('criar_loja', models.BooleanField(default=False)),
                ('criar_PDV', models.BooleanField(default=False)),
                ('criar_adiq', models.BooleanField(default=False)),
                ('criar_rota', models.BooleanField(default=False)),
                ('criar_band', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='servtef.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
