# Generated by Django 4.0.4 on 2022-08-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servtef', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariotef',
            name='criar_PDV',
        ),
        migrations.RemoveField(
            model_name='usuariotef',
            name='criar_adiq',
        ),
        migrations.RemoveField(
            model_name='usuariotef',
            name='criar_band',
        ),
        migrations.RemoveField(
            model_name='usuariotef',
            name='criar_empresa',
        ),
        migrations.RemoveField(
            model_name='usuariotef',
            name='criar_loja',
        ),
        migrations.RemoveField(
            model_name='usuariotef',
            name='criar_rota',
        ),
        migrations.RemoveField(
            model_name='usuariotef',
            name='criar_usuario',
        ),
        migrations.AddField(
            model_name='usuariotef',
            name='corporativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuariotef',
            name='operador_loja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuariotef',
            name='operador_pdv',
            field=models.BooleanField(default=False),
        ),
    ]
