# Generated by Django 4.0.4 on 2022-08-31 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servtef', '0002_remove_usuariotef_criar_pdv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariotef',
            name='loja',
            field=models.IntegerField(default=0),
        ),
    ]
