# Generated by Django 4.0.4 on 2022-09-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servtef', '0003_usuariotef_loja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariotef',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='usuariotef',
            name='corporativo',
        ),
        migrations.RemoveField(
            model_name='usuariotef',
            name='operador_loja',
        ),
        migrations.RemoveField(
            model_name='usuariotef',
            name='operador_pdv',
        ),
        migrations.AddField(
            model_name='usuariotef',
            name='perfil_user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
