# Generated by Django 4.0.4 on 2022-09-02 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servtef', '0004_remove_usuariotef_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nomeEmp',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuariotef',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useremp', to='servtef.empresa'),
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('codLoja', models.IntegerField(primary_key=True, serialize=False)),
                ('nomeLoja', models.CharField(max_length=50)),
                ('CNPJ', models.CharField(max_length=14)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lojaemp', to='servtef.empresa')),
            ],
        ),
    ]
