# Generated by Django 4.0.4 on 2022-09-03 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servtef', '0005_alter_empresa_nomeemp_alter_usuariotef_empresa_loja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariotef',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userloja', to='servtef.loja'),
        ),
    ]
