# Generated by Django 4.0.4 on 2022-09-07 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servtef', '0006_alter_usuariotef_loja'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDV',
            fields=[
                ('codPDV', models.IntegerField(primary_key=True, serialize=False)),
                ('UsuarioAtivo', models.IntegerField()),
                ('StatusPDV', models.BooleanField()),
                ('TransVendaCreditoVista', models.BooleanField()),
                ('TransVendaCreditoParc', models.BooleanField()),
                ('TransVendaCreditoSemJuros', models.BooleanField()),
                ('TransVendaDebito', models.BooleanField()),
                ('TransCancelamento', models.BooleanField()),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdvloja', to='servtef.loja')),
            ],
        ),
    ]
