# Generated by Django 4.0.4 on 2022-09-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servtef', '0007_pdv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdv',
            name='StatusPDV',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='TransCancelamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='TransVendaCreditoParc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='TransVendaCreditoSemJuros',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='TransVendaCreditoVista',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='TransVendaDebito',
            field=models.BooleanField(default=False),
        ),
    ]
