# Generated by Django 4.0.4 on 2022-09-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servtef', '0008_alter_pdv_statuspdv_alter_pdv_transcancelamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdv',
            name='TransCancelamento',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='TransVendaCreditoParc',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='TransVendaCreditoSemJuros',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='TransVendaCreditoVista',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='TransVendaDebito',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='UsuarioAtivo',
            field=models.IntegerField(null=True),
        ),
    ]
