# Generated by Django 4.0.4 on 2022-09-08 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servtef', '0009_alter_pdv_transcancelamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdv',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pdvemp', to='servtef.empresa'),
            preserve_default=False,
        ),
    ]
