# Generated by Django 4.0.4 on 2022-09-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servtef', '0010_pdv_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdv',
            name='codPDV',
            field=models.IntegerField(primary_key=False),
        ),
        migrations.AddField(
            model_name='pdv',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
