# Generated by Django 4.0.4 on 2022-09-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servtef', '0011_pdv_id_alter_pdv_codpdv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdv',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
