# Generated by Django 4.0.4 on 2022-09-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servtef', '0012_alter_pdv_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdv',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
