# Generated by Django 4.0.4 on 2022-09-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servtef', '0013_alter_pdv_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adquirente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codAdiq', models.IntegerField()),
                ('nomeAdiq', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='pdv',
            name='TransCancelamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='TransVendaCreditoParc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='TransVendaCreditoSemJuros',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='TransVendaCreditoVista',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='TransVendaDebito',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Bandeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codBan', models.IntegerField()),
                ('nomeBan', models.CharField(max_length=50)),
                ('Adquirentes', models.ManyToManyField(to='servtef.adquirente')),
            ],
        ),
    ]
