# Generated by Django 4.0.4 on 2022-09-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servtef', '0014_adquirente_alter_pdv_transcancelamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandeira',
            name='Adquirentes',
        ),
        migrations.AddField(
            model_name='adquirente',
            name='bandeiras',
            field=models.ManyToManyField(to='servtef.bandeira'),
        ),
    ]
