# Generated by Django 4.0.4 on 2022-09-15 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servtef', '0015_remove_bandeira_adquirentes_adquirente_bandeiras'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumLogico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numlogico', models.IntegerField()),
                ('adiq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logadiq', to='servtef.adquirente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logemp', to='servtef.empresa')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logloja', to='servtef.loja')),
            ],
        ),
    ]
