# Generated by Django 4.0.4 on 2022-09-18 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servtef', '0017_alter_numlogico_numlogico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roteamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adiq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotadiq', to='servtef.adquirente')),
                ('adiq2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotadiq2', to='servtef.adquirente')),
                ('bandeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotban', to='servtef.bandeira')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotemp', to='servtef.empresa')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotloja', to='servtef.loja')),
            ],
        ),
    ]
