# Generated by Django 4.0.4 on 2022-09-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servtef', '0018_roteamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdv',
            name='LastLogin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pdv',
            name='TransDigitado',
            field=models.BooleanField(default=False),
        ),
    ]
