# Generated by Django 4.0.4 on 2022-09-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servtef', '0019_pdv_lastlogin_pdv_transdigitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ultimoNSU',
            field=models.IntegerField(null=True),
        ),
    ]
