# Generated by Django 4.0.4 on 2022-09-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servtef', '0020_empresa_ultimonsu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='ultimoNSU',
            field=models.IntegerField(default=0),
        ),
    ]
