# Generated by Django 4.1.1 on 2022-10-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servtef', '0022_logtrans'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtrans',
            name='nomeAdiq',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logtrans',
            name='nomeBan',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
