# Generated by Django 4.1.1 on 2022-10-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servtef', '0023_logtrans_nomeadiq_logtrans_nomeban'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtrans',
            name='NSU_ConfDesfCanc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='logtrans',
            name='dataHoraConfDesfCanc',
            field=models.DateTimeField(null=True),
        ),
    ]
