# Generated by Django 4.1.1 on 2022-11-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servtef', '0024_logtrans_nsu_confdesfcanc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtrans',
            name='NSU_Canc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='logtrans',
            name='dataHoraCanc',
            field=models.DateTimeField(null=True),
        ),
    ]
