# Generated by Django 4.1.1 on 2022-11-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servtef', '0025_logtrans_nsu_canc_logtrans_datahoracanc'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtrans',
            name='numParcelas',
            field=models.IntegerField(null=True),
        ),
    ]
