# Generated by Django 4.1.1 on 2022-11-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servtef', '0026_logtrans_numparcelas'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('codPerfil', models.IntegerField(primary_key=True, serialize=False)),
                ('nomePerfil', models.CharField(max_length=20)),
            ],
        ),
    ]
