# Generated by Django 4.1.1 on 2022-12-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servtef', '0028_usuariotef_nome_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='URLServer',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='chave',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
