# Generated by Django 4.1.1 on 2023-03-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servtef', '0030_alter_loja_chave'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='endMail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='passMail',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
